# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addtobank.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from DatabaseMng import selector, creator

class Ui_MainWindow(QtWidgets.QMainWindow):
    def __init__(self):
        super().__init__()
        self.setupUi()
    def back_to_main(self):
        self.hide()
        self.window1.show()
    def back_to_main_manu(self, window1):
        self.window1 = window1
    def setupUi(self):
        self.setObjectName("Add to bank acc")
        self.resize(378, 246)
        self.setAcceptDrops(False)
        self.centralwidget = QtWidgets.QWidget(self)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 131, 16))
        self.label.setObjectName("label")
        self.idLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.idLineEdit.setGeometry(QtCore.QRect(110, 10, 241, 20))
        self.idLineEdit.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.idLineEdit.setObjectName("idLineEdit")
        self.idLineEdit.textChanged.connect(self.jmbg_selector)
        self.comboBoxAccNumber = QtWidgets.QComboBox(self.centralwidget)
        self.comboBoxAccNumber.setGeometry(QtCore.QRect(110, 80, 241, 22))
        self.comboBoxAccNumber.setObjectName("comboBoxAccNumber")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 80, 91, 16))
        self.label_2.setObjectName("label_2")
        self.pushButtonPayment = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonPayment.setGeometry(QtCore.QRect(110, 170, 75, 23))
        self.pushButtonPayment.setObjectName("pushButtonPayment")
        self.pushButtonPayment.clicked.connect(self.fincome)
        self.pushButtonWithdrawal = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonWithdrawal.setGeometry(QtCore.QRect(190, 170, 75, 23))
        self.pushButtonWithdrawal.setObjectName("pushButtonWithdrawal")
        self.pushButtonWithdrawal.clicked.connect(self.foutcome)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 110, 131, 16))
        self.label_3.setObjectName("label_3")
        self.Amount = QtWidgets.QLineEdit(self.centralwidget)
        self.Amount.setGeometry(QtCore.QRect(110, 110, 241, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Amount.sizePolicy().hasHeightForWidth())
        self.Amount.setSizePolicy(sizePolicy)
        self.Amount.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.Amount.setObjectName("Amount")
        self.pushButtonClose = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonClose.setGeometry(QtCore.QRect(280, 170, 75, 23))
        self.pushButtonClose.setObjectName("pushButtonClose")
        self.pushButtonClose.clicked.connect(self.back_to_main)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 140, 341, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(60, 40, 241, 16))
        self.label_5.setObjectName("label_5")
        self.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(self)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 378, 21))
        self.menubar.setObjectName("menubar")
        self.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(self)
        self.statusbar.setObjectName("statusbar")
        self.setStatusBar(self.statusbar)
        self.show_hide(False)
        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("Add to bank acc", "Add/Withdraw from bank account"))
        self.label.setText(_translate("Add to bank acc", "Personal ID number"))
        self.label_2.setText(_translate("Add to bank acc", "Bank Account NO"))
        self.pushButtonPayment.setText(_translate("Add to bank acc", "Payment"))
        self.pushButtonWithdrawal.setText(_translate("Add to bank acc", "Withdrawal"))
        self.label_3.setText(_translate("Add to bank acc", "Amount:"))
        self.pushButtonClose.setText(_translate("Add to bank acc", "Close"))
        self.label_4.setText(_translate("Add to bank acc", "The Value have been addeed to the bank account"))
        self.label_5.setText(_translate("Add to bank acc", "The account has not been found"))
        
    def jmbg_selector(self):
        
        if selector.JMBG_selector(self.idLineEdit.text()) == None:
            self.label_5.setText( "The account has not been found")
            self.show_hide(False)
        else:
            self.label_5.setText( "The user is in Database")
            self.show_hide(True)
            self.insert_combox()
            return selector.JMBG_selector(self.idLineEdit.text())
            
    def fincome(self):
        
        creator.add_money(int(self.comboBoxAccNumber.currentText()),float(self.Amount.text()) )
        self.Amount.clear()

       

    def insert_combox(self):
        m = selector.get_all_user_bank_ID(self.idLineEdit.text())
        for n in m:
            n = str(n).translate({ord(i): None for i in '(),'})
            self.comboBoxAccNumber.addItem(n)
        
    def foutcome(self):
        creator.add_money(int(self.comboBoxAccNumber.currentText()),0-float(self.Amount.text()))
        self.Amount.clear()


    def show_hide(self,chck):
        self.comboBoxAccNumber.setVisible(chck)
        self.Amount.setVisible(chck)
        self.label_2.setVisible(chck)
        self.label_3.setVisible(chck)
        self.label_4.setVisible(chck)
        self.pushButtonPayment.setVisible(chck)
        self.pushButtonWithdrawal.setVisible(chck)
        self.comboBoxAccNumber.setVisible(chck)
