# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DeleteAcount.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from DatabaseMng import selector, deleters


class Ui_DeleteAccount(QtWidgets.QMainWindow):
    def __init__(self):
        super().__init__()
        self.setupUi()
        

    def back_to_main(self):
        self.hide()
        self.window1.show()
    def back_to_main_manu(self, window1):
        self.window1 = window1
    def setupUi(self):
        self.setObjectName("DeleteAccount")
        self.resize(337, 232)
        self.centralwidget = QtWidgets.QWidget(self)
        self.centralwidget.setObjectName("centralwidget")
        self.Delete = QtWidgets.QPushButton(self.centralwidget)
        self.Delete.setGeometry(QtCore.QRect(20, 130, 291, 23))
        self.Delete.setObjectName("Delete")
        self.Delete.clicked.connect(self.delete)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 20, 91, 16))
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(100, 20, 211, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit.textChanged.connect(self.SearchbyID)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(100, 50, 151, 16))
        self.label_3.setObjectName("label_3")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 50, 47, 13))
        self.label_2.setObjectName("label_2")
        self.ClearAccount = QtWidgets.QPushButton(self.centralwidget)
        self.ClearAccount.setGeometry(QtCore.QRect(20, 160, 121, 23))
        self.ClearAccount.setObjectName("ClearAccount")
        self.ClearAccount.clicked.connect(self.cleaning)
        self.CloseWindow = QtWidgets.QPushButton(self.centralwidget)
        self.CloseWindow.setGeometry(QtCore.QRect(200, 160, 111, 23))
        self.CloseWindow.setObjectName("CloseWindow")
        self.CloseWindow.clicked.connect(lambda: QtWidgets.QApplication.instance().quit())
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(30, 80, 47, 13))
        self.label_4.setObjectName("label_4")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(100, 80, 211, 22))
        self.comboBox.setObjectName("comboBox")
        self.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(self)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 337, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(self)
        self.statusbar.setObjectName("statusbar")
        self.setStatusBar(self.statusbar)
        self.actionClear = QtWidgets.QAction(self)
        self.actionClear.setObjectName("actionClear")
        self.actionClose = QtWidgets.QAction(self)
        self.actionClose.setObjectName("actionClose")
        self.menuFile.addAction(self.actionClear)
        self.menuFile.addAction(self.actionClose)
        self.menubar.addAction(self.menuFile.menuAction())
        self.hidding(False)

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("DeleteAccount", "MainWindow"))
        self.Delete.setText(_translate("DeleteAccount", "Delete Bank Account"))
        self.label.setText(_translate("DeleteAccount", "Enter JMBG"))
        self.label_3.setText(_translate("DeleteAccount", "Not found"))
        self.label_2.setText(_translate("DeleteAccount", "User:"))
        self.ClearAccount.setText(_translate("DeleteAccount", "Clear"))
        self.CloseWindow.setText(_translate("DeleteAccount", "Close"))
        self.label_4.setText(_translate("DeleteAccount", "Acc No:"))
        self.menuFile.setTitle(_translate("DeleteAccount", "File"))
        self.actionClear.setText(_translate("DeleteAccount", "Clear"))
        self.actionClose.setText(_translate("DeleteAccount", "Close"))

    
    
    
    
    def comboboxfiller(self):
        
        
        m = selector.get_all_user_bank_ID(self.lineEdit.text())
              
        for n in m:
            n = str(n).translate({ord(i): None for i in '(),'})
            self.comboBox.addItem(n)

    def SearchbyID(self):
        
        
        if selector.get_all_user_bank_ID(self.lineEdit.text()) == None:
            pass
        else:
            self.comboBox.clear()
            m = selector.get_all_user_bank_ID(self.lineEdit.text())
            self.label_3.setText(m[0]+ " " +  m[1])
            self.comboboxfiller()
            self.hidding(True)
    def delete(self):
        try:
            deleters.Delete_Bank_ACC(int(self.comboBox.currentText()))
            self.SearchbyID()
        except:
            pass
    def hidding(self, Checker):
        self.label_3.setVisible(Checker)
        self.label_2.setVisible(Checker)
        self.label_4.setVisible(Checker)
        self.comboBox.setVisible(Checker)
        self.Delete.setVisible(Checker)
        self.ClearAccount.setVisible(Checker)
    def cleaning(self):
        self.comboBox.clear()
        self.lineEdit.clear()
        self.hidding(False)
