# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DeleteUser.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys

from DatabaseMng import selector, deleters

from PyQt5 import QtCore, QtGui, QtWidgets
from DatabaseMng import deleters, selector


class Ui_DeleteUser(QtWidgets.QMainWindow):
    def __init__(self):
        super().__init__()
        
        self.setupUi()
    def back_to_main(self):
        #self.hideElements(False)
        self.hide()
        self.window1.show()
    def back_to_main_manu(self, window1):
        self.window1 = window1
      
    def setupUi(self):
        self.setObjectName("DeleteUser")
        self.resize(282, 183)
        self.centralwidget = QtWidgets.QWidget(self)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 20, 91, 16))
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(90, 20, 171, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit.textChanged.connect(self.findUser)
        self.Delete = QtWidgets.QPushButton(self.centralwidget)
        self.Delete.setGeometry(QtCore.QRect(10, 80, 251, 23))
        self.Delete.setObjectName("Delete")
        self.Delete.clicked.connect(self.deleteAction)
        self.ClearAccount = QtWidgets.QPushButton(self.centralwidget)
        self.ClearAccount.setGeometry(QtCore.QRect(10, 110, 121, 23))
        self.ClearAccount.setObjectName("ClearAccount")
        self.ClearAccount.clicked.connect(self.clear)
        self.CloseWindow = QtWidgets.QPushButton(self.centralwidget)
        self.CloseWindow.setGeometry(QtCore.QRect(150, 110, 111, 23))
        self.CloseWindow.setObjectName("CloseWindow")
        self.CloseWindow.clicked.connect(self.back_to_main)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 50, 47, 13))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(100, 50, 151, 16))
        self.label_3.setObjectName("label_3")
        self.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(self)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 282, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(self)
        self.statusbar.setObjectName("statusbar")
        self.setStatusBar(self.statusbar)
        self.actionClear = QtWidgets.QAction(self)
        self.actionClear.setObjectName("actionClear")
        self.actionClose = QtWidgets.QAction(self)
        self.actionClose.setObjectName("actionClose")
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionClear)
        self.menuFile.addAction(self.actionClose)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("DeleteUser", "MainWindow"))
        self.label.setText(_translate("DeleteUser", "Enter JMBG"))
        self.Delete.setText(_translate("DeleteUser", "Delete Bank Account"))
        self.ClearAccount.setText(_translate("DeleteUser", "Clear"))
        self.CloseWindow.setText(_translate("DeleteUser", "Close"))
        self.label_2.setText(_translate("DeleteUser", "User:"))
        self.label_3.setText(_translate("DeleteUser", "Not found"))
        self.menuFile.setTitle(_translate("DeleteUser", "File"))
        self.actionClear.setText(_translate("DeleteUser", "Clear"))
        self.actionClose.setText(_translate("DeleteUser", "Close"))
        self.hideElements(False)
    
    
    def findUser(self):
        
        
        if selector.Get_All_User_Data(self.lineEdit.text()) == None:
           pass 
            
        else:
            try:
                print(selector.Get_All_User_Data(self.lineEdit.text()))
                
                self.hideElements(True)
                m = selector.Get_All_User_Data(self.lineEdit.text())
                self.label_3.setText(m[0]+ " " +  m[1])
                helper = [self.lineEdit.text()]
                x = []
                helper1 = selector.get_all_user_bank_ID1(helper)
                for n in helper1:
                    n = str(n).translate({ord(i): None for i in '(),'})
                    x.append(n)
                return x, helper
            except:
                pass  
    
    def deleteAction(self):
        
        m = self.findUser()
        try:
            deleters.Delete_Bank_user(m[0],m[1])
            self.hideElements(False)
            self.lineEdit.clear()
        except:
            pass        
    def clear(self):
        self.hideElements(False)
        self.label_3.setText("Not found")
        self.lineEdit.clear()

    def hideElements(self,check): 
        self.Delete.setVisible(check)
        self.ClearAccount.setVisible(check)
        self.Delete.setVisible(check)
        self.Delete.setVisible(check)
        self.label_2.setVisible(check)
        self.label_3.setVisible(check)
        


