# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'edit_user.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import  sys
from PyQt5 import QtCore, QtGui, QtWidgets
from DatabaseMng import selector, editors


class Ui_Edit_user(QtWidgets.QMainWindow):
    def __init__(self):
        super().__init__()
        self.setupUi()

    def setupUi(self):
        self.setObjectName("Edit_user")
        self.resize(323, 392)
        self.centralwidget = QtWidgets.QWidget(self)
        self.centralwidget.setObjectName("centralwidget")
        
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(20, 20, 211, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")

        self.JMBG = QtWidgets.QLineEdit(self.centralwidget)
        self.JMBG.setGeometry(QtCore.QRect(20, 50, 271, 20))
        self.JMBG.setObjectName("JMBG")
        self.JMBG.textChanged.connect(self.SearchbyID)

        
        
        self.firstName = QtWidgets.QLineEdit(self.centralwidget)
        self.firstName.setGeometry(QtCore.QRect(120, 80, 171, 20))
        self.firstName.setObjectName("firstName")
        self.firstName.setVisible(False)

        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(20, 200, 91, 16))
        
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_5.setVisible(False)

        self.dateEdit = QtWidgets.QDateEdit(self.centralwidget)
        self.dateEdit.setGeometry(QtCore.QRect(120, 170, 171, 22))
        self.dateEdit.setObjectName("dateEdit")
        self.dateEdit.setVisible(False)

        self.StateBirth = QtWidgets.QLineEdit(self.centralwidget)
        self.StateBirth.setGeometry(QtCore.QRect(120, 230, 171, 20))
        self.StateBirth.setObjectName("StateBirth")
        self.StateBirth.setVisible(False)

        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(20, 170, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_4.setVisible(False)

        self.addUser = QtWidgets.QPushButton(self.centralwidget)
        self.addUser.setGeometry(QtCore.QRect(20, 320, 91, 23))
        self.addUser.setObjectName("addUser")
        self.addUser.setVisible(False)
        self.addUser.clicked.connect(self.edit_button)

        
        self.adressofLiving = QtWidgets.QLineEdit(self.centralwidget)
        self.adressofLiving.setGeometry(QtCore.QRect(20, 280, 271, 20))
        self.adressofLiving.setObjectName("adressofLiving")
        self.adressofLiving.setVisible(False)
        
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 140, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_3.setVisible(False)
        self.closeButton = QtWidgets.QPushButton(self.centralwidget)
        self.closeButton.setGeometry(QtCore.QRect(210, 320, 81, 23))
        self.closeButton.setObjectName("closeButton")
        self.closeButton.clicked.connect(self.back_to_main)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 110, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_2.setVisible(False)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(20, 230, 101, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_6.setVisible(False)
        self.clearUSer = QtWidgets.QPushButton(self.centralwidget)
        self.clearUSer.setGeometry(QtCore.QRect(120, 320, 81, 23))
        self.clearUSer.setObjectName("clearUSer")
        self.clearUSer.setVisible(False)
        self.clearUSer.clicked.connect(self.clear)
        self.familyName = QtWidgets.QLineEdit(self.centralwidget)
        self.familyName.setGeometry(QtCore.QRect(120, 140, 171, 20))
        self.familyName.setObjectName("familyName")
        self.familyName.setVisible(False)
        self.middleName = QtWidgets.QLineEdit(self.centralwidget)
        self.middleName.setGeometry(QtCore.QRect(120, 110, 171, 20))
        self.middleName.setObjectName("middleName")
        self.middleName.setVisible(False)
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(20, 260, 211, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_8.setVisible(False)
        self.placeBirth = QtWidgets.QLineEdit(self.centralwidget)
        self.placeBirth.setGeometry(QtCore.QRect(120, 200, 171, 20))
        self.placeBirth.setObjectName("placeBirth")
        self.placeBirth.setVisible(False)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 80, 101, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label.setVisible(False)
        self.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(self)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 323, 21))
        self.menubar.setObjectName("menubar")
        self.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(self)
        self.statusbar.setObjectName("statusbar")
        self.setStatusBar(self.statusbar)

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("Edit_user", "Edit User"))
        self.label_5.setText(_translate("Edit_user", "Place of birth"))
        self.label_4.setText(_translate("Edit_user", "Date of birth"))
        self.addUser.setText(_translate("Edit_user", "Edit User"))
        self.label_7.setText(_translate("Edit_user", "Personal idetification number"))
        self.label_3.setText(_translate("Edit_user", "Family name"))
        self.closeButton.setText(_translate("Edit_user", "Close"))
        self.label_2.setText(_translate("Edit_user", "Middle name"))
        self.label_6.setText(_translate("Edit_user", "State of birth"))
        self.clearUSer.setText(_translate("Edit_user", "Clear"))
        self.label_8.setText(_translate("Edit_user", "Adreess of living"))
        self.label.setText(_translate("Edit_user", "First Name"))
    def back_to_main_manu(self, window1):
        self.window1 = window1
    def back_to_main(self):
        self.close()
        self.window1.show()

    
    
            
    def SearchbyID(self):
       
        
        if selector.Get_All_User_Data(self.JMBG.text()) == None:
            self.setVisibleElements(False)
        else:
            self.setVisibleElements(True)
            p = selector.Get_All_User_Data(self.JMBG.text())
            self.firstName.setText(p[0])
            self.middleName.setText(p[1])
            self.familyName.setText(p[2])
            self.dateEdit.setDate(QtCore.QDate.fromString(p[3],"yyyy-MM-dd"))
            self.placeBirth.setText(p[4])
            self.StateBirth.setText(p[5])
            self.adressofLiving.setText(p[6])
            
    def setVisibleElements(self, checker):
        self.firstName.setVisible(checker)
        self.label_5.setVisible(checker)
        self.dateEdit.setVisible(checker)
        self.StateBirth.setVisible(checker)
        self.label_3.setVisible(checker)
        self.addUser.setVisible(checker)
        self.label_2.setVisible(checker)
        self.label_6.setVisible(checker)
        self.clearUSer.setVisible(checker)
        self.familyName.setVisible(checker)
        self.middleName.setVisible(checker)
        self.label_8.setVisible(checker)
        self.placeBirth.setVisible(checker)
        self.label.setVisible(checker)
        self.label_4.setVisible(checker)
        self.adressofLiving.setVisible(checker)
    def clear(self):
        self.setVisibleElements(False)
        self.firstName.clear()
        self.middleName.clear()
        self.familyName.clear()
        self.placeBirth.clear()
        self.dateEdit.setDate(QtCore.QDate.currentDate())
        self.adressofLiving.clear()
        self.JMBG.clear()
        self.StateBirth.clear()

    def edit_button(self):
        return editors.Edit_User_Data(self,self.firstName.text(), self.middleName.text(), self.familyName.text(), self.dateEdit.date().toString("yyyy-MM-dd"),\
                                              self.placeBirth.text(), self.StateBirth.text(), self.JMBG.text(), self.adressofLiving.text())
        



