# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'iow.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from DatabaseMng import selector

class Ui_MainWindow(QtWidgets.QMainWindow):
    def __init__(self):
        super().__init__()
        self.setupUi()
    def back_to_main(self):
        self.hide()
        self.window1.show()
    def back_to_main_manu(self, window1):
        self.window1 = window1

    def setupUi(self):
        self.setObjectName("MainWindow")
        self.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(self)
        self.centralwidget.setObjectName("centralwidget")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(140, 80, 271, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.currentIndexChanged.connect(self.getData)
        self.jmbgLabel = QtWidgets.QLabel(self.centralwidget)
        self.jmbgLabel.setGeometry(QtCore.QRect(30, 30, 47, 13))
        self.jmbgLabel.setObjectName("jmbgLabel")
        self.accnoLabel = QtWidgets.QLabel(self.centralwidget)
        self.accnoLabel.setGeometry(QtCore.QRect(30, 90, 47, 13))
        self.accnoLabel.setObjectName("accnoLabel")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(140, 30, 271, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit.textChanged.connect(self.SearchbyID)
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(30, 120, 741, 361))
        self.tableWidget.setObjectName("tableWidget")
        
        self.lcearButton = QtWidgets.QPushButton(self.centralwidget)
        self.lcearButton.setGeometry(QtCore.QRect(610, 500, 75, 23))
        self.lcearButton.setObjectName("lcearButton")
        self.lcearButton.clicked.connect(lambda: self.cleanAll(True))
        self.CloseButton = QtWidgets.QPushButton(self.centralwidget)
        self.CloseButton.setGeometry(QtCore.QRect(690, 500, 75, 23))
        self.CloseButton.setObjectName("CloseButton")
        self.CloseButton.clicked.connect(self.back_to_main)
        self.nadsLabbel = QtWidgets.QLabel(self.centralwidget)
        self.nadsLabbel.setGeometry(QtCore.QRect(30, 60, 101, 16))
        self.nadsLabbel.setObjectName("nadsLabbel")
        self.userLabel = QtWidgets.QLabel(self.centralwidget)
        self.userLabel.setGeometry(QtCore.QRect(140, 60, 271, 16))
        self.userLabel.setObjectName("userLabel")
        self.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(self)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        self.menuClear = QtWidgets.QMenu(self.menubar)
        self.menuClear.setObjectName("menuClear")
        self.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(self)
        self.statusbar.setObjectName("statusbar")
        self.setStatusBar(self.statusbar)
        self.actionClear = QtWidgets.QAction(self)
        self.actionClear.setObjectName("actionClear")
        self.actionClose = QtWidgets.QAction(self)
        self.actionClose.setObjectName("actionClose")
        
        self.menuClear.addAction(self.actionClear)
        self.menuClear.addAction(self.actionClose)
        self.menubar.addAction(self.menuClear.menuAction())

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self)

    def setTable(self):
        pass

    def comboboxfiller(self):
        
        
        m = selector.get_all_user_bank_ID(self.lineEdit.text())
              
        for n in m:
            n = str(n).translate({ord(i): None for i in '(),'})
            self.comboBox.addItem(n)

    def SearchbyID(self):     
        if selector.get_all_user_bank_ID(self.lineEdit.text()) == []:
            self.cleanAll(False)
        else:
            self.comboBox.clear()
            m = selector.select_bank_user_data(self.lineEdit.text())
            self.userLabel.setText(m[0]+ ' ' + m[1])
            self.comboboxfiller()
     
    def getData(self):
        print(self.comboBox.currentText())
        
        rows = selector.getTransactions(self.comboBox.currentText())
        
        if rows:
            self.tableWidget.setColumnCount(len(rows[0])+1)
            self.tableWidget.setRowCount(len(rows))
            self.tableWidget.setHorizontalHeaderLabels(["Acc No", "Income/Outcome", "Timestamp", "Total"])
            self.tableWidget.setColumnWidth(0,120)
            self.tableWidget.setColumnWidth(1,120)
            self.tableWidget.setColumnWidth(2,120)
            self.tableWidget.setColumnWidth(3,120)
            pepisa = 0
            for ind_row, row in enumerate(rows):
                for ind_col, col in enumerate(row):
                    if ind_col == 1:
                        pepisa += col
                    item = QtWidgets.QTableWidgetItem(str(col))
                    self.tableWidget.setItem(ind_row,ind_col,item)
                    
                self.tableWidget.setItem(ind_row,3,QtWidgets.QTableWidgetItem(str(pepisa)))
            self.tableWidget.repaint()
            self.tableWidget.update()
        else:
            self.tableWidget.clear()
    
    
    def cleanAll(self, chck):
        self.tableWidget.clear()
        self.comboBox.clear()
        
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.userLabel.setText("User not found")
              
        self.tableWidget.repaint()
        self.tableWidget.update()
        if chck == True:
            self.lineEdit.clear()



    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.jmbgLabel.setText(_translate("MainWindow", "JMBG"))
        self.accnoLabel.setText(_translate("MainWindow", "Acc NO:"))
        self.lcearButton.setText(_translate("MainWindow", "Clear"))
        self.CloseButton.setText(_translate("MainWindow", "Close"))
        self.nadsLabbel.setText(_translate("MainWindow", "Name and surname"))
        self.userLabel.setText(_translate("MainWindow", "User not found"))
        self.menuClear.setTitle(_translate("MainWindow", "File"))
        self.actionClear.setText(_translate("MainWindow", "Clear"))
        self.actionClose.setText(_translate("MainWindow", "Close"))
