# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMainWindow,QApplication



class Ui_MainWindow(QMainWindow):
    def __init__(self):
        super().__init__()
        
        self.setupUi()
    
        
    def set_window(self,add_user,view_bankio,add_a_new_bank_account,deleta_a_bank_user, edit_user, calculate_credit, delete_acc, add_to_bank, bit_coin):
        self.add_user = add_user
        self.view_bankio = view_bankio
        self.add_a_new_bank_account = add_a_new_bank_account
        self.deleta_a_bank_user = deleta_a_bank_user
        self.edit_user = edit_user
        self.calcualete_credit = calculate_credit
        self.delete_acc = delete_acc
        self.add_to_bank = add_to_bank
        self.bit_coin = bit_coin

    def setupUi(self):
        self.setObjectName("MainWindow")
        self.resize(713, 737)
        self.centralwidget = QtWidgets.QWidget(self)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(480, 20, 211, 191))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.open_add_a_new_bank_acc)
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(250, 20, 211, 191))
        font = QtGui.QFont()
        font.setStrikeOut(False)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setIconSize(QtCore.QSize(80, 80))
        self.pushButton_2.setCheckable(False)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.clicked.connect(self.open_view_bankio)
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(20, 20, 211, 191))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_3.clicked.connect(self.open_add_a_new_user)
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(20, 230, 211, 191))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_4.clicked.connect(self.open_edit_a_user)
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(250, 230, 211, 191))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_5.clicked.connect(self.open_credit)
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(480, 230, 211, 191))
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_6.clicked.connect(self.open_delete_bank_acc)
        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_7.setGeometry(QtCore.QRect(20, 640, 671, 51))
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_8.setGeometry(QtCore.QRect(20, 440, 211, 191))
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_8.clicked.connect(self.open_bank_transaction)
        self.pushButton_9 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_9.setGeometry(QtCore.QRect(250, 440, 211, 191))
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_9.clicked.connect(self.open_credit_rating)
        self.pushButton_10 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_10.setGeometry(QtCore.QRect(480, 440, 211, 191))
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_10.clicked.connect(self.open_delete_a_bank_user) 

        self.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(self)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 713, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(self)
        self.statusbar.setObjectName("statusbar")
        self.setStatusBar(self.statusbar)
        self.actionAdd_new_Admin = QtWidgets.QAction(self)
        self.actionAdd_new_Admin.setShortcut("")
        self.actionAdd_new_Admin.setShortcutVisibleInContextMenu(True)
        self.actionAdd_new_Admin.setObjectName("actionAdd_new_Admin")
        
        self.actionClose = QtWidgets.QAction(self)
        self.actionClose.setObjectName("actionClose")
        self.menuFile.addAction(self.actionAdd_new_Admin)
        self.menuFile.addAction(self.actionClose)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Add new bank account"))
        self.pushButton_2.setText(_translate("MainWindow", "\n"
"View  bank income/outcome"))
        self.pushButton_3.setText(_translate("MainWindow", "Add a new user"))
        self.pushButton_4.setText(_translate("MainWindow", "Edit a user"))
        self.pushButton_5.setText(_translate("MainWindow", "Calculate credit "))
        self.pushButton_6.setText(_translate("MainWindow", "Delete the bank account"))
        self.pushButton_7.setText(_translate("MainWindow", "Close"))
        self.pushButton_8.setText(_translate("MainWindow", "Bank transactions"))
        self.pushButton_9.setText(_translate("MainWindow", "Bit COin"))
        self.pushButton_10.setText(_translate("MainWindow", "Delete a bank user"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionAdd_new_Admin.setText(_translate("MainWindow", "Add new Admin"))
        self.actionClose.setText(_translate("MainWindow", "Close"))

    def open_add_a_new_user(self):
        self.hide()
        self.add_user.show()
    def open_view_bankio(self):
        self.hide()
        self.view_bankio.show()
    def open_add_a_new_bank_acc(self):
        self.hide()
        self.add_a_new_bank_account.show()
    def open_edit_a_user(self):
        self.hide()
        self.edit_user.show()
    def open_credit(self):
        self.hide()
        self.calcualete_credit.show()
    def open_delete_bank_acc(self):
        self.hide()
        self.delete_acc.show()
    def open_bank_transaction(self):
        self.hide()
        self.add_to_bank.show()
    def open_credit_rating(self):
        self.hide()
        self.bit_coin.show()
    def open_delete_a_bank_user(self):
        self.hide()
        self.deleta_a_bank_user.show()

